This is makeindex, version 2.16 [TeX Live 2022] (kpathsea + Thai support).
Scanning style file ./template.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file template.acn....done (60 entries accepted, 0 rejected).
Sorting entries....done (392 comparisons).
Generating output file template.acr....done (37 lines written, 0 warnings).
Output written in template.acr.
Transcript written in template.alg.
